Jest
FordLabs/retroquest pull request #275
Opened 2021-03-22 02:24 UTC by rkennel

## Overview
Change unit testing framework from Jasmine to Jest.  Save 75% of time executing unit tests

Connects #274 

## Testing Instructions
Run the following commands and observe results
```
yarn unit
```
```
yarn unit-coverage
```
```
yarn unit-watch
```

## Note
4 of the test suites had no tests.  These were deleted.

2021-03-25 12:46 UTC, adandach requested changes
Awesome improvement. Definitely prefer jest over jasmine. 

I requested some changes inline. In addition, it looks like this PR introduces yarn? Please also update the README and `build.gradle` to use yarn.

Not required for approval: There are a lot of `@ts-ignore`s to deal with the use of `jest.fn`. Is this how we want to handle using `jest.fn` with TypeScript or is there a different approach we should take? Open for discussion.

2021-03-25 12:46 UTC, adandach commented on ui/package.json
>      "karma-jasmine-html-reporter": "~1.5.0",
```suggestion
```
Karma can be safely removed

2021-03-25 12:48 UTC, adandach commented on ui/src/app/modules/teams/services/board.service.spec.ts
> +import {Observable, Subject} from 'rxjs';
Probably better to just clean up the imports across all modified files.

2021-03-25 21:44 UTC, rkennel commented
> Awesome improvement. Definitely prefer jest over jasmine.
> 
> Required changes are commented below.
> 
> Not required for approval: There are a lot of `@ts-ignore`s to deal with the use of `jest.fn`. Is this how we want to handle using `jest.fn` with TypeScript or is there a different approach we should take? Open for discussion.

We could setup TS Lint such that it ignores unit tests.  The challenge is that jest.fn does some "magic" that does not play well with types

2021-03-26 20:32 UTC, rkennel commented
All requested changes have been made

TSLINT feedback will be added as a new issue

2021-03-26 20:39 UTC, rkennel commented on ui/src/app/modules/teams/services/save-checker.service.ts
> +    this._lastSavedDateTime = `${now.getHours()}:${now.getMinutes().toString().padStart(2, '0')} ${ampm}`;
Reverted Change now uses moment again

2021-03-26 20:41 UTC, rkennel commented on ui/src/app/modules/teams/services/websocket.service.spec.ts
> +    // });
Done

2021-03-26 20:49 UTC, adandach approved these changes

2021-03-26 21:45 UTC, merged