Replace ColumnTitle With Column ID on Thought
FordLabs/retroquest pull request #416
Opened 2022-04-04 18:49 UTC by LowBudgetMan

## Overview
* Added columnId to the Thought object to handle Thought -> Column relationship
* Made it impossible to add a Thought not tied to a column
* Removed ColumnTitle from Thought object
* Simplify the information passed through a CreateThoughtRequest
* Archived Boards now show all columns even if there are no Thoughts in them

### Notes
Would love another set of eyes on the database migration script. Seemd to work fine when I ran it against my containerized Postgres instance, but another look couldn't hurt.

The next step will be removing the reference to Topic on Thought. Then the only thing tying the two objects together is the column_id foreign key. That should hopefully make the Thought less dependant on the specific columns that a team has, leading to potentially more columns being allowed or different column types.

## Testing Instructions
The application should behave the same as it did before, with the exception viewing an archived board. An archived board should now have all the columns displayed regardless of whether or not there are thoughts in it.

2022-04-04 20:04 UTC, RandomAshes commented on ui/cypress/e2e/archivist-journey.spec.ts
> +		console.log(getColumnsForTeam(teamCredentials.teamId));
Can probably remove the console log

2022-04-05 15:37 UTC, tsatam requested changes

2022-04-05 18:20 UTC, LowBudgetMan commented on api/src/main/java/com/ford/labs/retroquest/board/BoardService.java
>          return this.boardRepository.findAllByTeamIdOrderByDateCreatedDesc(teamId,
Made #417 to handle this.

2022-04-05 18:20 UTC, LowBudgetMan commented on api/src/main/java/com/ford/labs/retroquest/team/TeamService.java
> +        var columns = columnTitleRepository.findAllByTeamId(team).stream().map(Column::fromColumnTitle).collect(Collectors.toList());
Made #417 to handle this

2022-04-07 20:12 UTC, tsatam approved these changes

2022-04-08 15:34 UTC, merged